/*
 * Intentionally wrong CBLAS Level 3 library.
 * Purpose: demonstrate expected interface test failures for the extra task.
 * The functions have the same CBLAS names and signatures, but they do not perform
 * the required BLAS operations.
 */
#include <cblas.h>
#define UNUSED(x) (void)(x)

void openblas_set_num_threads(int num_threads) { UNUSED(num_threads); }

void cblas_sgemm(CBLAS_LAYOUT layout, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, const CBLAS_INT M, const CBLAS_INT N, const CBLAS_INT K, const float alpha, const float *A, const CBLAS_INT lda, const float *B, const CBLAS_INT ldb, const float beta, float *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(TransA); UNUSED(TransB); UNUSED(M); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_dgemm(CBLAS_LAYOUT layout, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, const CBLAS_INT M, const CBLAS_INT N, const CBLAS_INT K, const double alpha, const double *A, const CBLAS_INT lda, const double *B, const CBLAS_INT ldb, const double beta, double *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(TransA); UNUSED(TransB); UNUSED(M); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_cgemm(CBLAS_LAYOUT layout, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, const CBLAS_INT M, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(TransA); UNUSED(TransB); UNUSED(M); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zgemm(CBLAS_LAYOUT layout, CBLAS_TRANSPOSE TransA, CBLAS_TRANSPOSE TransB, const CBLAS_INT M, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(TransA); UNUSED(TransB); UNUSED(M); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }

void cblas_ssymm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, const CBLAS_INT M, const CBLAS_INT N, const float alpha, const float *A, const CBLAS_INT lda, const float *B, const CBLAS_INT ldb, const float beta, float *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_dsymm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, const CBLAS_INT M, const CBLAS_INT N, const double alpha, const double *A, const CBLAS_INT lda, const double *B, const CBLAS_INT ldb, const double beta, double *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_csymm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zsymm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }

void cblas_chemm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zhemm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }

void cblas_ssyrk(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const float alpha, const float *A, const CBLAS_INT lda, const float beta, float *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_dsyrk(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const double alpha, const double *A, const CBLAS_INT lda, const double beta, double *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_csyrk(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zsyrk(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_cherk(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const float alpha, const void *A, const CBLAS_INT lda, const float beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zherk(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const double alpha, const void *A, const CBLAS_INT lda, const double beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(beta); UNUSED(C); UNUSED(ldc); }

void cblas_ssyr2k(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const float alpha, const float *A, const CBLAS_INT lda, const float *B, const CBLAS_INT ldb, const float beta, float *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_dsyr2k(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const double alpha, const double *A, const CBLAS_INT lda, const double *B, const CBLAS_INT ldb, const double beta, double *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_csyr2k(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zsyr2k(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const void *beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_cher2k(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const float beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }
void cblas_zher2k(CBLAS_LAYOUT layout, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE Trans, const CBLAS_INT N, const CBLAS_INT K, const void *alpha, const void *A, const CBLAS_INT lda, const void *B, const CBLAS_INT ldb, const double beta, void *C, const CBLAS_INT ldc) { UNUSED(layout); UNUSED(Uplo); UNUSED(Trans); UNUSED(N); UNUSED(K); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); UNUSED(beta); UNUSED(C); UNUSED(ldc); }

void cblas_strmm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const float alpha, const float *A, const CBLAS_INT lda, float *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
void cblas_dtrmm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const double alpha, const double *A, const CBLAS_INT lda, double *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
void cblas_ctrmm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, void *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
void cblas_ztrmm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, void *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }

void cblas_strsm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const float alpha, const float *A, const CBLAS_INT lda, float *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
void cblas_dtrsm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const double alpha, const double *A, const CBLAS_INT lda, double *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
void cblas_ctrsm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, void *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
void cblas_ztrsm(CBLAS_LAYOUT layout, CBLAS_SIDE Side, CBLAS_UPLO Uplo, CBLAS_TRANSPOSE TransA, CBLAS_DIAG Diag, const CBLAS_INT M, const CBLAS_INT N, const void *alpha, const void *A, const CBLAS_INT lda, void *B, const CBLAS_INT ldb) { UNUSED(layout); UNUSED(Side); UNUSED(Uplo); UNUSED(TransA); UNUSED(Diag); UNUSED(M); UNUSED(N); UNUSED(alpha); UNUSED(A); UNUSED(lda); UNUSED(B); UNUSED(ldb); }
